### PR TITLE
Move VPA from channel per version to stable channel

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Review by wangchen615 — APPROVED** [review]
/lgtm

**Comment by joelsmith** [comment]
/hold cancel
I was too slow to add /hold but we'll revert any/all of these changes if necessary.
The question we still have is about whether on manifests/dirname, does dirname refer to a version or a channel name. So we may need to go back to how we had it before for much of this change. Thanks @wangchen615 for catching that.

**Pull request merged**
