### PR TITLE
Bug 2086731: [ART-4049] Bump to 4.11

### PR DESCRIPTION
**Pull request by locriandev**
[Test build](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45334852) passed
Ref. [ART-4049](https://issues.redhat.com/browse/ART-4049)

### CODE REVIEW

**Comment by locriandev** [comment]
Rebased by taking out channel rename to 'stable'

**Comment by jupierce** [comment]
@locriandev has tried everything he can to get this merged cleanly. It will require component team work to understand these test failures at this point. 
/lgtm

**Pull request merged**
