### PR TITLE
Bump dependencies version

### PR DESCRIPTION
**Pull request by QiWang19**
Update go module dependencies and remove Gopkg files.
Add context argument under pkg/operator since introduced by new dependency (github.com/openshift/client-go imports  k8s.io/client-go).

### CODE REVIEW

**Comment by joelsmith** [comment]
Sorry, I didn't mean for the bot to close this. Now that openshift/release#17035 merged, hopefully the tests will pass.

**Comment by joelsmith** [comment]
Thanks @QiWang19 for updating everything for us!

/lgtm
/approve

**Review by wangchen615 — APPROVED** [review]

**Pull request merged**
