### PR TITLE
PODAUTO-99: Updates for 4.16 

### PR DESCRIPTION
**Pull request by jkyros**
Updates for 4.16

- Update deps
    - edit (update to 4.16/0.29.0) and run hack/update-vendor.sh
- Update code and build to match updated deps
- Update go version to go 1.21 (go.mod, Dockerfile, images/ci/Dockerfile, Makefile, vet, lint)
- Rev version from 4.15 -> 4.16:  
    `sed -i 's/4.15/4.16/g' $(git grep -l 4.15 manifests/) images/ci/bundle.Dockerfile hack/manifest-diff-upstream.sh hack/e2e.sh Makefile`
- Verify that Dockerfile.rhel7 & .ci-operator.yaml are up to date (they are. [Thanks, ART team](https://github.com/openshift/vertical-pod-autoscaler-operator/pull/151)!)
- Update manifests to match upstream

I also had to do some additional one-off surgery: 
- The move to conroller-runtime 0.17.0 messed with how the cache worked, so I had to fill in some of our NamespacedNames because the namespaced cache doesn't do it automatically anymore (I held us at 0.15.2 last time to postpone it until I understood the failure, but it's handled now) 
- The CVO retired some of their helper functions ( https://github.com/openshift/cluster-version-operator/pull/1012/commits/77075ae3f665f7775ce48de91ddad76d52accda6) but we were still using them, so I pulled them into our own `lib/resourcemerge` 
- The upstream test suite changed and was pickier about the environment (node schedulability, directory mutability) so I had to adjust a couple of our command line options so the tests wouldn't fail immediately on setup

### CODE REVIEW

**Comment by jkyros** [comment]
Yep, that's what I was worried about. Just configuring the default namespaces in the new controller-runtime isn't good enough, it looks like maybe we were freeloading off something else in the old behavior. I'll figure it out next week: 
```
E0210 03:20:22.845247       1 status.go:316] Error getting VerticalPodAutoscalerController: unable to get: /default because of unknown namespace for the cache
W0210 03:20:22.845263       1 status.go:226] Operator status degraded: error checking VPA controllers status: unable to get: /default because of unknown namespace for the cache
E0210 03:20:37.844984       1 status.go:316] Error getting VerticalPodAutoscalerController: unable to get: /default because of unknown namespace for the cache
W0210 03:20:37.845001       1 status.go:226] Operator status degraded: error checking VPA controllers status: unable to get: /default because of unknown namespace for the cache
E0210 03:20:52.845005       1 status.go:316] Error getting VerticalPodAutoscalerController: unable to get: /default because of unknown namespace for the cache
W0210 03:20:52.845024       1 status.go:226] Operator status degraded: error checking VPA controllers status: unable to get: /default because of unknown namespace for the cache
E0210 03:21:07.845086       1 status.go:316] Error getting VerticalPodAutoscalerController: unable to get: /default because of unknown namespace for the cache
W0210 03:21:07.845103       1 status.go:226] Operator status degraded: error checking VPA controllers status: unable to get: /default because of unknown namespace for the cache
E0210 03:21:22.845002       1 status.go:316] Error getting VerticalPodAutoscalerController: unable to get: /default because of unknown namespace for the cache
W0210 03:21:22.845024       1 status.go:226] Operator status degraded: error checking VPA controllers status: unable to get: /default because of unknown namespace for the cache
```

**Comment by jkyros** [comment]
Yeah, it looks like there were a couple spots where we didn't fill the namespace into the namespacedname, and the old cache used to just kind of assume the default namespace because it could only handle one, but the new cache doesn't do that anymore. 
/test e2e-aws-operator

**Comment by jkyros** [comment]
That might be a flake, but it's entirely possible the upstream test changed: 
```
{ failed [FAILED] timed out waiting for the condition
In [SynchronizedBeforeSuite] at: /tmp/tmp.J4s7R4xkJU/src/k8s.io/autoscaler/vertical-pod-autoscaler/e2e/v1/e2e.go:220 @ 02/10/24 09:30:58.864
}
```

/test e2e-aws-operator

**Comment by jkyros** [comment]
CI is having trouble pulling images today, I gave it a bit, let's try again
/test e2e-aws-operator

**Comment by jkyros** [comment]
I don't know what changed in the upstream test, but it is now upset about the 3 masters that aren't schedulable. 
/test e2e-aws-operator

**Comment by jkyros** [comment]
helps if I actually commit the right vendored deps :smile: 
/test all

**Comment by jkyros** [comment]
`e2e-aws-olm` and `e2e-aws-operator` won't pass until  https://github.com/openshift/kubernetes-autoscaler/pull/286 merges

**Comment by joelsmith** [comment]
Whew! This one was trickier than the average version update. Thanks for tracking everything down and cleaning up the messes!

/lgtm

**Pull request merged**
